/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package examples.folder;

/**
 *
 * @author Baby_
 */
public class entexts {
    String [] x = {"Agitator: Career Entries: Burgher, Captain, Herald, Highwayman, Scribe, Servant, Student, Zealot ; Career Exits: Charlatan, Demagogue, Outlaw, Politician, Rogue, Zealot",
"Apprentice Wizard: Career Entries: Hedge Wizard, Scholar, Scribe, Student ; Career Exits: Journeyman Wizard, Scholar, Scribe",
"Bailiff: Career Entries: Bodyguard, Jailer ; Career Exits: Militiaman, Politician, Protagonist, Racketeer, Smuggler, Toll Keeper",
"Barber-Surgeon: Career Entries: Initiate, Student ; Career Exits: Interrogator, Grave Robber, Physician, Tradesman, Vagabond",
"Boatman: Career Entries: Ferryman, Smuggler ; Career Exits: Fisherman, Marine, Navigator, Seaman, Smuggler",
"Bodyguard: Career Entries: Estalian Diestro, Jailer, Mercenary, Thug ;  Career Exits: Bailiff, Bounty Hunter, Interrogator, Jailer, Mercenary, Protagonist, Racketeer",
"Bone Picker: Career Entries: Peasant, Rat Catcher, Vagabond ;  Career Exits: Camp Follower, Cat Burglar, Fence, Grave Robber, Smuggler",
"Bounty Hunter: Career Entries: Bodyguard, Fieldwarden, Hunter, Kislevite Kossar, Mercenary, Pit Fighter  ;  Career Exits: Mercenary, Protagonist, Scout, Targeteer, Vampire Hunter",
"Burgher: Career Entries: Innkeeper, Servant  ;  Career Exits: Agitator, Fence, Innkeeper, Merchant, Militiaman, Tradesman, Valet",
"Camp Follower: Career Entries: Bone Picker, Servant  ;  Career Exits: Charcoal-Burner, Charlatan, Servant, Smuggler, Spy, Tradesman, Vagabond",
"Charcoal-Burner: Career Entries: Camp Follower, Hunter, Miner, Peasant  ;  Career Exits: Hunter, Miner, Scout, Vagabond, Woodsman",
"Coachman: Career Entries: Outrider, Messenger  ;  Career Exits: Ferryman, Highwayman, Outlaw, Roadwarden, Scout, Smuggler, Toll Keeper",
"Entertainer: Career Entries: Herald, Rogue, Thief, Vagabond  ;  Career Exits: Charlatan, Minstrel, Rogue, Thief, Vagabond",
"Envoy: Career Entries: Student, Tradesman  ;  Career Exits: Charlatan, Merchant, Rogue, Seaman, Student, Vagabond",
"Estalian Diestro: Career Entries: None  ;  Career Exits: Bodyguard, Duellist, Highwayman, Protagonist, Rogue",
"Ferryman: Career Entries: Coachman, Smuggler, Toll Keeper  ;  Career Exits: Boatman, Highwayman, Roadwarden, Seaman, Smuggler",
"Fieldwarden: Career Entries: Hunter, Militiaman, Toll Keeper  ;  Career Exits: Bounty Hunter, Mercenary, Scout, Vagabond, Vampire Hunter",
"Fisherman: Career Entries: Boatman, Peasant  ;  Career Exits: Marine, Merchant, Militiaman, Navigator, Seaman",
"Grave Robber: Career Entries: Barber-Surgeon, Bone Picker, Rat Catcher  ;  Career Exits: Cat Burglar, Fence, Rat Catcher, Student, Thief",
"Hedge Wizard: Career Entries: None  ;  Career Exits: Apprentice Wizard, Charlatan, Initiate, Outlaw, Vagabond",
"Hunter: Career Entries: Charcoal-Burner, Kithband Warrior, Woodsman  ;  Career Exits: Bounty Hunter, Charcoal-Burner, Fieldwarden, Kithband Warrior, Miner, Scout, Soldier, Targeteer",
"Initiate: Career Entries: Hedge Wizard, Knight, Scribe, Student, Vampire Hunter, Witch Hunter, Zealot  ;  Career Exits: Barber-Surgeon, Demagogue, Friar, Priest, Scribe, Zealot",
"Jailer: Career Entries: Bodyguard, Rat Catcher  ;  Career Exits: Bailiff, Bodyguard, Interrogator, Rat Catcher, Watchman",
"Kislevite Kossar: Career Entries: None  ;  Career Exits: Bounty Hunter, Mercenary, Sergeant, Shieldbreaker, Veteran",
"Kithband Warrior: Career Entries: Hunter, Messenger  ;  Career Exits: Hunter, Outrider, Scout, Vagabond, Veteran",
"Marine: Career Entries: Boatman, Fisherman, Seaman  ;  Career Exits: Mate, Outlaw, Sergeant, Smuggler, Thug",
"Mercenary: Career Entries: Bodyguard, Bounty Hunter, Demagogue, Fieldwarden, Kislevite Kossar, Militiaman, Miner, Norse Berserker, Outrider, Pit Fighter, Soldier, Thug, Watchman  ;  Career Exits: Bodyguard, Bounty Hunter, Outlaw, Sergeant, Shieldbreaker, Veteran",
"Messenger: Career Entries: Militiaman, Roadwarden, Servant  ;  Career Exits: Coachman, Herald, Kithband Warrior, Outrider, Roadwarden, Scout, Soldier",
"Militiaman: Career Entries: Artisan, Bailiff, Burgher, Fisherman, Merchant, Peasant, Tradesman, Woodsman ; Career Exits: Artisan, Fieldwarden, Mercenary, Messenger, Outlaw, Sergeant, Thief",
"Miner: Career Entries: Charcoal-Burner, Hunter  ;  Career Exits: Charcoal-Burner, Engineer, Mercenary, Scout, Shieldbreaker, Smuggler",
"Noble: Career Entries: Squire, Steward  ;  Career Exits: Courtier, Pistolier, Politician, Rogue, Squire, Student",
"Norse Berserker: Career Entries: None ;  Career Exits: Mercenary, Pit Fighter, Seaman, Sergeant, Veteran",
"Outlaw: Career Entries: Agitator, Charlatan, Coachman, Hedge Wizard, Innkeeper, Marine, Mercenary, Militiaman, Peasant, Roadwarden, Rogue, Squire, Toll Keeper, Woodsman, Zealot  ;  Career Exits: Demagogue, Highwayman, Thief, Vagabond, Veteran",
"Outrider: Career Entries: Kithband Warrior, Messenger, Roadwarden, Soldier  ;  Career Exits: Coachman, Highwayman, Mercenary, Roadwarden, Scout",
"Peasant: Career Entries: None  ;  Career Exits: Bone Picker, Charcoal-Burner, Fisherman, Militiaman, Outlaw, Politician, Servant, Tradesman, Zealot",
"Pit Fighter: Career Entries: Norse Berserker, Protagonist, Shieldbreaker, Thug  ;  Career Exits: Bounty Hunter, Mercenary, Protagonist, Troll Slayer, Veteran",
"Protagonist: Career Entries: Bailiff, Bodyguard, Bounty Hunter, Estalian Diestro, Pit Fighter  ;  Career Exits: Duellist, Pit Fighter, Racketeer, Thief, Thug",
"Rat Catcher: Career Entries: Grave Robber, Jailer, Runebearer, Tomb Robber  ;  Career Exits: Bone Picker, Cat Burglar, Grave Robber, Jailer, Shieldbreaker, Thief",
"Roadwarden: Career Entries: Coachman, Ferryman, Messenger, Outrider, Watchman  ;  Career Exits: Highwayman, Messenger, Outlaw, Outrider, Scout, Sergeant, Toll Keeper",
"Rogue: Career Entries: Agitator, Assassin, Duellist, Entertainer, Envoy, Estalian Diestro, Noble, Seaman, Thief, Valet  ;  Career Exits: Charlatan, Demagogue, Entertainer, Outlaw, Servant, Thief",
"Runebearer: Career Entries: Shieldbreaker  ;  Career Exits: Rat Catcher, Scout, Shieldbreaker, Tomb Robber, Veteran",
"Scribe: Career Entries: Apprentice Wizard, Initiate ;  Career Exits: Agitator, Apprentice Wizard, Initiate, Navigator, Scholar",
"Seaman: Career Entries: Boatman, Envoy, Ferryman, Fisherman, Norse Berserker, Smuggler  ;  Career Exits: Marine, Mate, Navigator, Rogue, Smuggler",
"Servant: Career Entries: Camp Follower, Peasant, Rogue  ;  Career Exits: Agitator, Burgher, Camp Follower, Innkeeper, Messenger, Spy, Thief, Valet",
"Shieldbreaker: Career Entries: Kislevite Kossar, Mercenary, Miner, Rat Catcher, Runebearer, Smuggler, Tomb Robber  ;  Career Exits: Pit Fighter, Runebearer, Sergeant, Smuggler, Tomb Robber, Veteran",
"Smuggler: Career Entries: Bailiff, Boatman, Bone Picker, Camp Follower, Coachman, Engineer, Ferryman, Innkeeper, Marine, Miner, Seaman, Shieldbreaker  ;  Career Exits: Boatman, Charlatan, Fence, Ferryman, Seaman, Shieldbreaker, Thief",
"Soldier: Career Entries: Flagellant, Hunter, Messenger, Toll Keeper, Watchman  ;  Career Exits: Mercenary, Outrider, Sergeant, Vagabond, Veteran, Watchman",
"Squire: Career Entries: Herald, Noble, Valet  ;  Career Exits: Knight, Noble, Outlaw, Sergeant, Veteran",
"Student: Career Entries: Envoy, Grave Robber, Minstrel, Noble, Valet ;  Career Exits: Agitator, Apprentice Wizard, BarberSurgeon, Engineer, Envoy, Initiate, Physician, Scholar",
"Thief: Career Entries: Entertainer, Grave Robber, Interrogator, Militiaman, Outlaw, Protagonist, Rat Catcher, Rogue, Servant, Smuggler, Toll Keeper, Tomb Robber, Vagabond ;  Career Exits: Cat Burglar, Charlatan, Entertainer, Fence, Rogue, Tomb Robber",
"Thug: Career Entries: Marine, Protagonist ;  Career Exits: Bodyguard, Interrogator, Mercenary, Pit Fighter, Racketeer",
"Toll Keeper: Career Entries: Bailiff, Coachman, Roadwarden ;  Career Exits: Ferryman, Fieldwarden, Highwayman, Outlaw, Soldier, Politician, Thief",
"Tomb Robber: Career Entries: Runebearer, Shieldbreaker, Thief ;  Career Exits: Fence, Rat Catcher, Shieldbreaker, Thief, Vampire Hunter",
"Tradesman: Career Entries: Barber-Surgeon, Burgher, Camp Follower, Peasant, Watchman ;  Career Exits: Artisan, Engineer, Envoy, Merchant, Militiaman, Zealot",
"Troll Slayer: Career Entries: Pit Fighter ;  Career Exits: Giant Slayer",
"Vagabond: Career Entries: Barber-Surgeon, Camp Follower, Cat Burglar, Charcoal-Burner, Entertainer, Envoy, Fieldwarden, Hedge Wizard, Kithband Warrior, Outlaw, Soldier, Woodsman ;  Career Exits: Bone Picker, Entertainer, Friar, Scout, Thief, Woodsman",
"Valet: Career Entries: Burgher, Servant ;  Career Exits: Herald, Rogue, Squire, Steward, Student",
"Watchman: Career Entries: Jailer, Soldier ;  Career Exits: Mercenary, Racketeer, Roadwarden, Sergeant, Soldier, Tradesman",
"Woodsman: Career Entries: Charcoal-Burner, Vagabond ;  Career Exits: Hunter, Militiaman, Outlaw, Scout, Vagabond",
"Zealot: Career Entries: Agitator, Initiate, Judicial Champion, Peasant, Tradesman ; Career Exits: Agitator, Initiate, Flagellant, Friar, Outlaw"};
}
